import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/landing/Footer';

export default function TermsOfServicePage() {
  return (
    <div className="dark bg-background text-foreground">
      <Navbar />
      <main className="container mx-auto px-4 py-24 sm:py-32">
        <article className="prose prose-invert lg:prose-xl mx-auto">
          <h1>Terms of Service</h1>
          <p className="lead">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

          <p>Please read these Terms of Service ("Terms") carefully before using the FastFind360 service ("Service") operated by FastFind360 ("us", "we", or "our").</p>

          <h2>1. Agreement to Terms</h2>
          <p>By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service. This agreement applies to all visitors, users, and others who access or use the Service.</p>

          <h2>2. Service Description</h2>
          <p>FastFind360 provides a property intelligence platform that utilizes satellite imagery, AI-powered classification, and data analytics to provide insights for governments, financial institutions, and real estate professionals. The data provided is for informational and analytical purposes and should not be considered as a sole source for financial or legal decisions.</p>

          <h2>3. User Accounts</h2>
          <p>When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service.</p>

          <h2>4. Intellectual Property</h2>
          <p>The Service and its original content, features, and functionality are and will remain the exclusive property of FastFind360 and its licensors. The Service is protected by copyright, trademark, and other laws of both Nigeria and foreign countries. Our trademarks may not be used in connection with any product or service without the prior written consent of FastFind360.</p>
          
          <h2>5. Use of Data</h2>
          <p>You may use the data and reports generated by the Service for your internal business purposes, in accordance with your subscription level. You agree not to resell, reproduce, or distribute the data provided by the Service without our express written permission. Data exported from the Service remains subject to these Terms.</p>

          <h2>6. Limitation of Liability</h2>
          <p>In no event shall FastFind360, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>

          <h2>7. Governing Law</h2>
          <p>These Terms shall be governed and construed in accordance with the laws of the Federal Republic of Nigeria, without regard to its conflict of law provisions.</p>
          
          <h2>8. Changes</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
          
          <h2>9. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at legal@fastfind360.com.</p>
        </article>
      </main>
      <Footer />
    </div>
  );
}
